replicaCount: 1

displayName: Everton

image:
  repository: evearakaki/app
  tag: stable
  pullPolicy: Always
  containerPort: 3000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host:
      paths: 
        - /app